const inventory = require('../lib/plugins/inventory')
const events = require('events')
let bot = {}
bot._client = new events.EventEmitter()
inventory(bot)
// console.log(bot.checkItem(JSON.parse('{"action":0,"category":22,"id":133,"equipped":0,"in_socket":0,"identified":1,"switched_in":0,"switched_out":0,"broken":0,"potion":0,"has_sockets":0,"in_store":1,"not_in_a_socket":0,"ear":0,"start_item":0,"simple_item":1,"ethereal":0,"personalised":0,"gambling":0,"rune_word":0,"version":101,"ground":true,"x":5887,"y":5064,"unspecified_directory":false,"type":"hp1","name":"Minor Healing Potion","width":"1","height":"1","throwable":"0","stackable":"0","usable":"1","is_armor":false,"is_weapon":false,"quality":2}')))
console.log(`Pick elrune ? ${bot.checkItem(JSON.parse('{"name": "elrune"}'))}`)
console.log(bot.checkItem(JSON.parse('{"action":4,"category":39,"id":27,"equipped":0,"in_socket":0,"identified":1,"switched_in":0,"switched_out":0,"broken":0,"potion":0,"has_sockets":0,"in_store":0,"not_in_a_socket":0,"ear":0,"start_item":0,"simple_item":0,"ethereal":0,"personalised":0,"gambling":0,"rune_word":0,"version":101,"ground":false,"directory":0,"x":7,"y":6,"container":2,"unspecified_directory":false,"type":"rin","name":"Ring","width":"1","height":"1","throwable":"0","stackable":"0","usable":"0","is_armor":false,"is_weapon":false,"quality":13,"level":56,"has_graphic":1,"graphic":5,"has_colour":0,"amount":9,"properties":[{"stat":"pierce_idx","value":0},{"stat":"maximum_mana","value":89},{"stat":"slain_monsters_rest_in_peace","value":0},{"stat":"mana_per_time","value":1336342},{"stat":"skill_stamina_percent","value":0},{"stat":"enemy_fire_resistance_reduction","value":204}]}')))
console.log(`Pick ? ${bot.checkItem(JSON.parse('{"action":4,"category":20,"id":526,"equipped":0,"in_socket":0,"identified":1,"switched_in":0,"switched_out":0,"broken":0,"potion":0,"has_sockets":0,"in_store":0,"not_in_a_socket":0,"ear":0,"start_item":0,"simple_item":1,"ethereal":0,"personalised":0,"gambling":0,"rune_word":0,"version":101,"ground":false,"directory":0,"x":5,"y":7,"container":2,"unspecified_directory":false,"type":"r04","name":"Nef Rune","width":"1","height":"1","throwable":"0","stackable":"0","usable":"0","is_armor":false,"is_weapon":false,"quality":2}'))}`)
